version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Excute Create Cfn Stack
          command: |
            aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
            aws cloudformation wait stack-create-complete --stack-name sample-stack
　ansible_playbook:
    exeutor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install:
          version: 2.9.27
      - add_ssh_keys:
          fingerprints:
            - "fd:75:91:83:8d:3c:be:bc:bb:82:b9:91:fa:d0:d4:9e"
      - ansible-playbook/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user
          private-key: ANSIBLE_SSH_KEY
workflows:
  infrastructure-ci:
    jobs:
      - aws_cli
      - ansible_playbook:
          requires:
            - "aws_cli"