# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  
#jobs定義はsay　hallo(自分たちで命名する、ジョブは)をdockerのイメージを使用して実行環境を構築する、その中でやる処理は
#stepsにかかれていてcheckout、ソースコードを実行環境にクローンしていく
#name: say halloについた実行コマンドを、表示するeho hello world
jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup 
      - run:
          name: Excute Create Cfn Stack
          command: |
            aws cloudformation create-stack --stack-name sample-stack --template-body file://service/infrastructure.yml
workflows:
  infrastructure-ci:
    jobs:
      - aws_cli
 