version: 2.1

#jobs定義はsay　hallo(自分たちで命名する、ジョブは)をdockerのイメージを使用して実行環境を構築する、その中でやる処理は
#stepsにかかれていてcheckout、ソースコードを実行環境にクローンしていく
#name: say halloについた実行コマンドを、表示するeho hello world
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

#workflowsのsay-hello-workflowを命名する、say-hello-workflowの中にはjobsキーを設定して配列形式でどう言ったjobsw
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
